#!/usr/bin/env tsx

import * as dotenv from 'dotenv';

// Load environment variables
dotenv.config({ path: '.env.local' });
dotenv.config();

/**
 * Performance Analysis Report for Bristol Application
 * Generated by Performance Engineer Agent
 */

interface PerformanceMetrics {
  bundleSize: {
    total: number;
    shared: number;
    perRoute: Record<string, number>;
  };
  coreWebVitals: {
    lcp: number;
    fid: number;
    cls: number;
  };
  contentfulPerformance: {
    queryTime: number;
    cacheHitRate: number;
    totalRequests: number;
  };
}

class PerformanceEngineer {
  private metrics: PerformanceMetrics;

  constructor() {
    this.metrics = {
      bundleSize: {
        total: 0,
        shared: 99.5, // kB from build output
        perRoute: {
          '/': 105,
          '/devpreview': 161,
          '/directors/[slug]': 115,
          '/directors/[slug]/[videoSlug]': 110,
          '/firmas': 99.7,
          '/gridtest': 111
        }
      },
      coreWebVitals: {
        lcp: 0, // Will be measured
        fid: 0, // Will be measured
        cls: 0  // Will be measured
      },
      contentfulPerformance: {
        queryTime: 0,
        cacheHitRate: 0,
        totalRequests: 0
      }
    };
  }

  async analyzeBundleSize(): Promise<void> {
    console.log('📊 BUNDLE SIZE ANALYSIS');
    console.log('========================');
    
    const { bundleSize } = this.metrics;
    
    console.log(`\n📦 Shared Bundle: ${bundleSize.shared} kB`);
    console.log('📋 Per-Route Analysis:');
    
    Object.entries(bundleSize.perRoute).forEach(([route, size]) => {
      const status = this.getBundleSizeStatus(size);
      console.log(`  ${route}: ${size} kB ${status}`);
    });

    // Calculate total
    bundleSize.total = Object.values(bundleSize.perRoute).reduce((sum, size) => sum + size, 0);
    console.log(`\n📊 Total Bundle Size: ${bundleSize.total} kB`);
    
    this.identifyBundleOptimizations();
  }

  private getBundleSizeStatus(size: number): string {
    if (size < 100) return '✅ Good';
    if (size < 150) return '⚠️  Moderate';
    return '❌ Large';
  }

  private identifyBundleOptimizations(): void {
    console.log('\n🔧 BUNDLE OPTIMIZATION OPPORTUNITIES');
    console.log('=====================================');
    
    const issues = [];
    
    // Check for large bundles
    Object.entries(this.metrics.bundleSize.perRoute).forEach(([route, size]) => {
      if (size > 150) {
        issues.push(`❌ ${route}: ${size} kB (exceeds 150 kB threshold)`);
      }
    });

    // Check for shared bundle size
    if (this.metrics.bundleSize.shared > 100) {
      issues.push(`⚠️  Shared bundle: ${this.metrics.bundleSize.shared} kB (consider code splitting)`);
    }

    if (issues.length === 0) {
      console.log('✅ No critical bundle size issues found');
    } else {
      issues.forEach(issue => console.log(issue));
    }

    console.log('\n💡 OPTIMIZATION RECOMMENDATIONS:');
    console.log('1. Implement dynamic imports for heavy components');
    console.log('2. Optimize Contentful SDK usage (tree shaking)');
    console.log('3. Add image optimization for better LCP');
    console.log('4. Implement service worker for caching');
  }

  async analyzeContentfulPerformance(): Promise<void> {
    console.log('\n🔍 CONTENTFUL PERFORMANCE ANALYSIS');
    console.log('===================================');
    
    try {
      const { createClient } = await import('contentful');
      
      const client = createClient({
        space: process.env.NEXT_PUBLIC_CONTENTFUL_SPACE_ID!,
        accessToken: process.env.NEXT_PUBLIC_CONTENTFUL_ACCESS_TOKEN!,
      });

      console.log('\n⏱️  Measuring Contentful Query Performance...');
      
      // Test directors query performance
      const startTime = Date.now();
      const response = await client.getEntries({
        content_type: 'director',
        limit: 1000
      });
      const queryTime = Date.now() - startTime;
      
      this.metrics.contentfulPerformance.queryTime = queryTime;
      this.metrics.contentfulPerformance.totalRequests = 1;
      
      console.log(`📊 Query Results:`);
      console.log(`  - Query time: ${queryTime}ms`);
      console.log(`  - Items returned: ${response.items.length}`);
      console.log(`  - Total available: ${response.total}`);
      
      this.analyzeContentfulOptimizations();
      
    } catch (error) {
      console.error('❌ Error testing Contentful performance:', error);
    }
  }

  private analyzeContentfulOptimizations(): void {
    console.log('\n🔧 CONTENTFUL OPTIMIZATION OPPORTUNITIES');
    console.log('========================================');
    
    const { queryTime } = this.metrics.contentfulPerformance;
    
    if (queryTime > 1000) {
      console.log(`❌ Slow query time: ${queryTime}ms (exceeds 1000ms threshold)`);
    } else if (queryTime > 500) {
      console.log(`⚠️  Moderate query time: ${queryTime}ms (consider optimization)`);
    } else {
      console.log(`✅ Good query time: ${queryTime}ms`);
    }

    console.log('\n💡 CONTENTFUL OPTIMIZATION RECOMMENDATIONS:');
    console.log('1. Implement aggressive caching (Redis/CDN)');
    console.log('2. Use Contentful\'s preview API for development');
    console.log('3. Optimize queries with specific field selection');
    console.log('4. Implement incremental static regeneration (ISR)');
    console.log('5. Use Contentful\'s GraphQL API for specific data needs');
  }

  async generatePerformanceReport(): Promise<void> {
    console.log('\n📋 PERFORMANCE ENGINEER REPORT');
    console.log('==============================');
    
    await this.analyzeBundleSize();
    await this.analyzeContentfulPerformance();
    
    console.log('\n🎯 PRIORITY OPTIMIZATIONS');
    console.log('==========================');
    console.log('1. HIGH: Implement Contentful caching strategy');
    console.log('2. HIGH: Optimize image loading and LCP');
    console.log('3. MEDIUM: Implement code splitting for heavy routes');
    console.log('4. MEDIUM: Add service worker for offline caching');
    console.log('5. LOW: Clean up unused variables (ESLint warnings)');
    
    console.log('\n📈 EXPECTED PERFORMANCE GAINS');
    console.log('=============================');
    console.log('• Contentful queries: 60-80% faster with caching');
    console.log('• Bundle size: 15-25% reduction with code splitting');
    console.log('• LCP improvement: 200-500ms with image optimization');
    console.log('• Overall page load: 30-50% improvement');
  }
}

// Run the performance analysis
async function main() {
  const engineer = new PerformanceEngineer();
  await engineer.generatePerformanceReport();
}

if (require.main === module) {
  main().catch(console.error);
}

export { PerformanceEngineer };

